server:
  port: ${PORT:8085}

jobs:
  default-schedule: "1 * * * * ?"

  friends:
    active: false
    path: "datasources/fakefriends.csv"

  weather:
    active: false
    path: "datasources/1800.csv"
    filter-type: TMAX #TMIN

  wordcount:
    simple-wordcount:
      active: false
      path: "datasources/book.txt"

  financial:
    order-processing:
      active: false
      path: "datasources/customer-orders.csv"

  movie:
    most-popular-movie:
      active: false
      path: "datasources/movies/ratings.csv"
    most-rated-movie:
      active: false
      path: "datasources/movies/ratings.csv"
    movie-similarities:
      active: false
      path: "datasources/movies/ratings.csv"
      score-threshold: 0.97
      coOccurence-threshold: 50.0
      similitude-movie: 50

  superheroes:
    most-popular-hero:
      active: false
      main-data-path: "datasources/Marvel-graph.txt"
      additional-data-path: "datasources/Marvel-names.txt"

dfjobs:
  city:
    active: false
    path: "datasources/df/CitiGroup2006_2008"
  sales:
    active: false
    path: "datasources/df/Sales.csv"
  netflix:
    active: true
    path: "datasources/df/Netflix_2011_2016.csv"

logging:
  file: application.log
